version: 2.1
orbs:
  node: circleci/node@4.3.0
commands:
  test:
    parameters:
      workspace:
        enum:
          - codec
          - serial
        type: enum
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn << parameters.workspace >> test
      - run: yarn << parameters.workspace >> cov:send
jobs:
  codec-test:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - test:
          workspace: codec
  serial-test:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - test:
          workspace: serial
  serial-build:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
workflows:
  test:
    jobs:
      - codec-test
      - serial-build
